### ISSUE TITLE
complete team

### ISSUE THREAD

**Issue by orbeckst** [ASU-CompMethodsPhysics-PHY494/final-2017-openthepodbaydoors_hal#2]
@ASU-CompMethodsPhysics-PHY494/openthepodbaydoors_hal  I think one of your team members has not signed up yet. Please make sure that *everyone* is part of the team and the GitHub repo.

**Comment by orbeckst** [comment]
If your team only consists of two members then please quickly let me know in a comment on this issue and then close the issue.

**Comment by orbeckst** [comment]
@Pazookii @AZAkyla is there a team member missing?

**Comment by CalebMadsen** [comment]
Hey so I clicked the link and joined this team but it doesn't appear I am actually part of the team.

**Comment by orbeckst** [comment]
We'll look at this after class today, please remind me (and bring your team mates).

> On 18 Apr, 2017, at 12:27, CalebMadsen <notifications@github.com> wrote:
> 
> Hey so I clicked the link and joined this team but it doesn't appear I am actually part of the team.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by orbeckst** [comment]
You are part of the team – I can assign you to the issue.
